Update header
StudieverenigingSTORM/BAPC21-theme pull request #14
Opened 2021-09-17 13:05 UTC by iMylene

2021-09-17 13:50 UTC, mvr320 commented
Did you check the resulting folder?

2021-09-18 16:19 UTC, EuiYeonJang approved these changes

2021-09-18 17:31 UTC, mvr320 requested changes
you need to change the rgba values here to something as the svg is using black and this is also black

2021-09-20 08:54 UTC, mvr320 approved these changes

2021-09-20 08:54 UTC, merged